class S:
    teams = {
    "cowboys": ("Dallas Cowboys", 81),
    "dallascowboys": ("Dallas Cowboys", 81),
    "dallas": ("Dallas Cowboys", 81),
    "eagles": ("Philadelphia Eagles", 90),
    "philadelphiaeagles": ("Philadelphia Eagles", 90),
    "philadelphia": ("Philadelphia Eagles", 90),
    "giants": ("New York Giants", 78),
    "newyorkgiants": ("New York Giants", 78),
    "commanders": ("Washington Commanders", 79),
    "washingtoncommanders": ("Washington Commanders", 79),
    "washington": ("Washington Commanders", 79),
    "bears": ("Chicago Bears", 84),
    "chicagobears": ("Chicago Bears", 84),
    "chicago": ("Chicago Bears", 84),
    "lions": ("Detroit Lions", 87),
    "detroitlions": ("Detroit Lions", 87),
    "detroit": ("Detroit Lions", 87),
    "packers": ("Green Bay Packers", 83),
    "greenbaypackers": ("Green Bay Packers", 83),
    "greenbay": ("Green Bay Packers", 83),
    "vikings": ("Minnesota Vikings", 85),
    "minnesotavikings": ("Minnesota Vikings", 85),
    "minnesota": ("Minnesota Vikings", 85),
    "falcons": ("Atlanta Falcons", 80),
    "atlantafalcons": ("Atlanta Falcons", 80),
    "atlanta": ("Atlanta Falcons", 80),
    "panthers": ("Carolina Panthers", 80),
    "carolinapanthers": ("Carolina Panthers", 80),
    "carolina": ("Carolina Panthers", 80),
    "saints": ("New Orleans Saints", 77),
    "neworleanssaints": ("New Orleans Saints", 77),
    "neworleans": ("New Orleans Saints", 77),
    "buccaneers": ("Tampa Bay Buccaneers", 83),
    "tampabaybuccaneers": ("Tampa Bay Buccaneers", 83),
    "tampabay": ("Tampa Bay Buccaneers", 83),
    "tampa": ("Tampa Bay Buccaneers", 83),
    "cardinals": ("Arizona Cardinals", 80),
    "arizonacardinals": ("Arizona Cardinals", 80),
    "arizona": ("Arizona Cardinals", 80),
    "rams": ("Los Angeles Rams", 89),
    "losangelesrams": ("Los Angeles Rams", 89),
    "fortyniners": ("San Francisco 49ers", 84),
    "49ers": ("San Francisco 49ers", 84),
    "sanfrancisco49ers": ("San Francisco 49ers", 84),
    "sanfrancisco": ("San Francisco 49ers", 84),
    "seahawks": ("Seattle Seahawks", 85),
    "seattleseahawks": ("Seattle Seahawks", 85),
    "seattle": ("Seattle Seahawks", 85),
    "bills": ("Buffalo Bills", 88),
    "buffalobills": ("Buffalo Bills", 88),
    "buffalo": ("Buffalo Bills", 88),
    "dolphins": ("Miami Dolphins", 79),
    "miamidolphins": ("Miami Dolphins", 79),
    "miami": ("Miami Dolphins", 79),
    "patriots": ("New England Patriots", 86),
    "newenglandpatriots": ("New England Patriots", 86),
    "newengland": ("New England Patriots", 86),
    "jets": ("New York Jets", 74),
    "newyorkjets": ("New York Jets", 74),
    "ravens": ("Baltimore Ravens", 87),
    "baltimoreravens": ("Baltimore Ravens", 87),
    "baltimore": ("Baltimore Ravens", 87),
    "bengals": ("Cincinnati Bengals", 81),
    "cincinnatibengals": ("Cincinnati Bengals", 81),
    "cincinnati": ("Cincinnati Bengals", 81),
    "browns": ("Cleveland Browns", 81),
    "clevelandbrowns": ("Cleveland Browns", 81),
    "cleveland": ("Cleveland Browns", 81),
    "steelers": ("Pittsburgh Steelers", 84),
    "pittsburghsteelers": ("Pittsburgh Steelers", 84),
    "pittsburgh": ("Pittsburgh Steelers", 84),
    "texans": ("Houston Texans", 86),
    "houstontexans": ("Houston Texans", 86),
    "houston": ("Houston Texans", 86),
    "colts": ("Indianapolis Colts", 82),
    "indianapoliscolts": ("Indianapolis Colts", 82),
    "indianapolis": ("Indianapolis Colts", 82),
    "jaguars": ("Jacksonville Jaguars", 84),
    "jacksonvillejaguars": ("Jacksonville Jaguars", 84),
    "jacksonville": ("Jacksonville Jaguars", 84),
    "titans": ("Tennessee Titans", 75),
    "tennesseetitans": ("Tennessee Titans", 75),
    "tennessee": ("Tennessee Titans", 75),
    "broncos": ("Denver Broncos", 91),
    "denverbroncos": ("Denver Broncos", 91),
    "denver": ("Denver Broncos", 91),
    "chiefs": ("Kansas City Chiefs", 85),
    "kansascitychiefs": ("Kansas City Chiefs", 85),
    "kansascity": ("Kansas City Chiefs", 85),
    "raiders": ("Las Vegas Raiders", 76),
    "lasvegasraiders": ("Las Vegas Raiders", 76),
    "lasvegas": ("Las Vegas Raiders", 76),
    "chargers": ("Los Angeles Chargers", 82),
    "losangeleschargers": ("Los Angeles Chargers", 82),
    }
